tive que fazer uma adaptação do modelo do wooldridge, baixei manualmente os dados a partir de 2014 (onde tem o código da uf e todas as variáveis disponíveis), e como não tenho o uso de cigarros, vou fazer uma análise a partir de hipóteses, vou pegar 1% de cada ano para analisar sem sobrecarregar o computador

hipóteses:

1️⃣ Idade materna

Hipótese: Idade materna muito baixa (<20 anos) ou muito alta (≥35 anos) ↑ probabilidade de baixo peso ao nascer.
Variáveis independentes:

IDADEMAE (criar categorias: <20, 20–34, ≥35)

2️⃣ Escolaridade materna

Hipótese: Menor escolaridade da mãe ↑ risco de baixo peso ao nascer.
Variáveis independentes:

ESCMAE ou ESCMAEAGR1 (anos de estudo ou categorias: sem escolaridade, fundamental, médio, superior)

3️⃣ Assistência pré-natal

Hipótese: Menos consultas de pré-natal ↑ risco de baixo peso.
Variáveis independentes:

CONSULTAS ou CONSPRENAT (número de consultas ou categorias: nenhuma, 1–3, 4–6, 7+)

MESPRENAT (mês de início do pré-natal)

KOTELCHUCK (índice de adequação do pré-natal)

4️⃣ Tipo de gravidez

Hipótese: Gravidez múltipla (gêmeos ou mais) ↑ risco de baixo peso.
Variáveis independentes:

GRAVIDEZ (1 = única, 2 = dupla, 3+ = tripla ou mais)

QTDPARTNOR / QTDPARTCES (número de partos anteriores, para controlar efeito histórico)

5️⃣ Tipo de parto e prematuridade

Hipótese: Cesárea eletiva antes de 37 semanas ↑ risco de baixo peso.
Variáveis independentes:

PARTO (1 = vaginal, 2 = cesáreo)

STCESPARTO (cesárea antes do trabalho de parto)

SEMAGESTAC ou GESTACAO (semanas de gestação, para definir prematuridade <37)

6️⃣ Sexo do bebê

Hipótese: Bebês do sexo feminino têm maior probabilidade de baixo peso ao nascer.
Variáveis independentes:

SEXO (1 = masculino, 2 = feminino)

7️⃣ Raça/cor da mãe

Hipótese: Crianças nascidas de mães negras ou pardas ↑ risco de baixo peso (associado a desigualdades socioeconômicas e acesso à saúde).
Variáveis independentes:

RACACORMAE ou RACACOR (tipos de raça/cor da mãe)

8️⃣ Número de gestações anteriores

Hipótese: Nulíparas ou mulheres com muitas gestações anteriores ↑ risco de baixo peso.
Variáveis independentes:

QTDGESTANT (número de gestações anteriores)

QTDFILVIVO (número de filhos vivos)

QTDFILMORT (número de perdas fetais anteriores)

9️⃣ Local de nascimento / assistência ao parto

Hipótese: Nascimentos em domicílio ou locais com menos infraestrutura ↑ risco de baixo peso.
Variáveis independentes:

LOCNASC (1 = hospital, 2 = outro estabelecimento, 3 = domicílio, etc.)

TPFUNCRESP (profissional que realizou registro: médico, enfermeiro, parteira)

10️⃣ Prematuridade

Hipótese: Prematuridade (menos de 37 semanas) ↑ risco de baixo peso.
Variáveis independentes:

SEMAGESTAC ou GESTACAO (semanas de gestação)

Pode criar variável binária: prematuro = 1 (<37 semanas), 0 caso contrário

Tratamento dos dados:

In [1]:
import glob
import pandas as pd

In [2]:
files = glob.glob("data/SINASC_20*.csv")
sampled_data = []

for f in files:
    print(f)
    for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
        sampled_data.append(chunk.sample(frac=0.01, random_state=42))
    
    
df = pd.concat(sampled_data, ignore_index=True)

data\SINASC_2014.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):

data\SINASC_2015.csv
data\SINASC_2016.csv
data\SINASC_2017.csv
data\SINASC_2018.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):

data\SINASC_2019.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (24) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):

data\SINASC_2020.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):

data\SINASC_2021.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):

data\SINASC_2022.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (24,32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):

data\SINASC_2023.csv

C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):
C:\Users\yasmi\AppData\Local\Temp\ipykernel_9188\2880192570.py:6: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(f, encoding="ISO-8859-1", sep=';', chunksize=100000):

In [3]:
for df in sampled_data:
    df.columns = df.columns.str.upper()

In [7]:
df_final = pd.DataFrame()

for df in sampled_data:
    df_final = pd.concat([df_final, df])

In [8]:
df_final.columns

Index(['CONTADOR', 'ORIGEM', 'CODESTAB', 'CODMUNNASC', 'LOCNASC', 'IDADEMAE',
       'ESTCIVMAE', 'ESCMAE', 'CODOCUPMAE', 'QTDFILVIVO', 'QTDFILMORT',
       'CODMUNRES', 'GESTACAO', 'GRAVIDEZ', 'PARTO', 'CONSULTAS', 'DTNASC',
       'HORANASC', 'SEXO', 'APGAR1', 'APGAR5', 'RACACOR', 'PESO', 'IDANOMAL',
       'DTCADASTRO', 'CODANOMAL', 'NUMEROLOTE', 'VERSAOSIST', 'DTRECEBIM',
       'DIFDATA', 'DTRECORIGA', 'NATURALMAE', 'CODMUNNATU', 'CODUFNATU',
       'ESCMAE2010', 'SERIESCMAE', 'DTNASCMAE', 'RACACORMAE', 'QTDGESTANT',
       'QTDPARTNOR', 'QTDPARTCES', 'IDADEPAI', 'DTULTMENST', 'SEMAGESTAC',
       'TPMETESTIM', 'CONSPRENAT', 'MESPRENAT', 'TPAPRESENT', 'STTRABPART',
       'STCESPARTO', 'TPNASCASSI', 'TPFUNCRESP', 'TPDOCRESP', 'DTDECLARAC',
       'ESCMAEAGR1', 'STDNEPIDEM', 'STDNNOVA', 'CODPAISRES', 'TPROBSON',
       'PARIDADE', 'KOTELCHUCK', 'OPORT_DN'],
      dtype='object')

In [9]:
# filtrando colunas úteis
colunas = ['PESO','IDADEMAE', 'ESCMAE2010', 'CONSULTAS', 'CONSPRENAT', 'MESPRENAT', 'KOTELCHUCK', 'GRAVIDEZ', 'QTDPARTNOR', 'QTDPARTCES', 'PARTO', 'STCESPARTO', 'SEMAGESTAC', 'GESTACAO', 'SEXO', 'RACACORMAE', 'PARIDADE', 'DTCADASTRO', 'RACACOR', 'QTDFILVIVO', 'QTDFILMORT']
df_final = df_final.filter(colunas)
df_final

,PESO,IDADEMAE,ESCMAE2010,CONSULTAS,CONSPRENAT,MESPRENAT,KOTELCHUCK,GRAVIDEZ,QTDPARTNOR,QTDPARTCES,...,STCESPARTO,SEMAGESTAC,GESTACAO,SEXO,RACACORMAE,PARIDADE,DTCADASTRO,RACACOR,QTDFILVIVO,QTDFILMORT
75721,3000.0,18.0,4.0,3.0,6.0,3.0,4,1.0,0.0,0.0,...,NaN,38.0,5.0,F,4.0,0,15012014.0,4.0,0.0,0.0
80184,3994.0,35.0,3.0,3.0,5.0,5.0,2,1.0,0.0,2.0,...,2.0,38.0,5.0,F,4.0,1,19022014.0,4.0,2.0,1.0
19864,2820.0,32.0,1.0,3.0,6.0,3.0,4,1.0,1.0,NaN,...,NaN,38.0,5.0,M,NaN,1,19052014.0,NaN,1.0,NaN
76699,3000.0,17.0,2.0,4.0,7.0,3.0,5,1.0,1.0,NaN,...,NaN,43.0,6.0,F,4.0,1,20022014.0,4.0,1.0,NaN
92991,2690.0,21.0,4.0,3.0,6.0,2.0,4,1.0,NaN,NaN,...,NaN,39.0,5.0,F,4.0,0,10062014.0,4.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2523997,3230.0,37.0,5.0,4.0,11.0,2.0,5,1.0,0.0,1.0,...,2.0,39.0,5.0,1,4.0,1,11102023.0,4.0,1.0,0.0
2513355,3155.0,25.0,2.0,4.0,8.0,2.0,5,1.0,0.0,1.0,...,3.0,35.0,4.0,1,4.0,1,22012024.0,4.0,1.0,0.0
2509738,3040.0,24.0,5.0,4.0,9.0,2.0,5,1.0,0.0,1.0,...,2.0,38.0,5.0,1,4.0,1,5022024.0,4.0,1.0,0.0
2530066,3410.0,37.0,5.0,4.0,12.0,2.0,5,1.0,0.0,0.0,...,2.0,39.0,5.0,2,1.0,1,2122023.0,1.0,0.0,1.0
2510508,3795.0,26.0,3.0,4.0,10.0,1.0,5,1.0,1.0,0.0,...,3.0,39.0,5.0,2,1.0,1,12032024.0,1.0,1.0,0.0

In [10]:
df = df_final.copy()

In [11]:
# convertendo o formato correto em data

# 1️⃣ converter para inteiro e depois string sem casas decimais
df['dt_str'] = df['DTCADASTRO'].fillna(0).astype(int).astype(str)

# 2️⃣ preencher com zeros à esquerda (sempre 8 dígitos: ddmmyyyy)
df['DT_NASC'] = df['dt_str'].str.zfill(8)

# 3️⃣ converter para datetime
df['DT_NASC'] = pd.to_datetime(df['dt_str'], format='%d%m%Y', errors='coerce')

df = df.drop(columns=['DTCADASTRO', 'dt_str']).reset_index(drop=True)
df

,PESO,IDADEMAE,ESCMAE2010,CONSULTAS,CONSPRENAT,MESPRENAT,KOTELCHUCK,GRAVIDEZ,QTDPARTNOR,QTDPARTCES,...,STCESPARTO,SEMAGESTAC,GESTACAO,SEXO,RACACORMAE,PARIDADE,RACACOR,QTDFILVIVO,QTDFILMORT,DT_NASC
0,3000.0,18.0,4.0,3.0,6.0,3.0,4,1.0,0.0,0.0,...,NaN,38.0,5.0,F,4.0,0,4.0,0.0,0.0,2014-01-15
1,3994.0,35.0,3.0,3.0,5.0,5.0,2,1.0,0.0,2.0,...,2.0,38.0,5.0,F,4.0,1,4.0,2.0,1.0,2014-02-19
2,2820.0,32.0,1.0,3.0,6.0,3.0,4,1.0,1.0,NaN,...,NaN,38.0,5.0,M,NaN,1,NaN,1.0,NaN,2014-05-19
3,3000.0,17.0,2.0,4.0,7.0,3.0,5,1.0,1.0,NaN,...,NaN,43.0,6.0,F,4.0,1,4.0,1.0,NaN,2014-02-20
4,2690.0,21.0,4.0,3.0,6.0,2.0,4,1.0,NaN,NaN,...,NaN,39.0,5.0,F,4.0,0,4.0,NaN,NaN,2014-06-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280785,3230.0,37.0,5.0,4.0,11.0,2.0,5,1.0,0.0,1.0,...,2.0,39.0,5.0,1,4.0,1,4.0,1.0,0.0,2023-10-11
280786,3155.0,25.0,2.0,4.0,8.0,2.0,5,1.0,0.0,1.0,...,3.0,35.0,4.0,1,4.0,1,4.0,1.0,0.0,2024-01-22
280787,3040.0,24.0,5.0,4.0,9.0,2.0,5,1.0,0.0,1.0,...,2.0,38.0,5.0,1,4.0,1,4.0,1.0,0.0,2024-02-05
280788,3410.0,37.0,5.0,4.0,12.0,2.0,5,1.0,0.0,0.0,...,2.0,39.0,5.0,2,1.0,1,1.0,0.0,1.0,2023-02-21
280789,3795.0,26.0,3.0,4.0,10.0,1.0,5,1.0,1.0,0.0,...,3.0,39.0,5.0,2,1.0,1,1.0,1.0,0.0,2024-03-12

In [15]:
df.to_csv('data/dados.csv')

In [13]:
df

,PESO,IDADEMAE,ESCMAE2010,CONSULTAS,CONSPRENAT,MESPRENAT,KOTELCHUCK,GRAVIDEZ,QTDPARTNOR,QTDPARTCES,...,STCESPARTO,SEMAGESTAC,GESTACAO,SEXO,RACACORMAE,PARIDADE,RACACOR,QTDFILVIVO,QTDFILMORT,DT_NASC
0,3000.0,18.0,4.0,3.0,6.0,3.0,4,1.0,0.0,0.0,...,NaN,38.0,5.0,F,4.0,0,4.0,0.0,0.0,2014-01-15
1,3994.0,35.0,3.0,3.0,5.0,5.0,2,1.0,0.0,2.0,...,2.0,38.0,5.0,F,4.0,1,4.0,2.0,1.0,2014-02-19
2,2820.0,32.0,1.0,3.0,6.0,3.0,4,1.0,1.0,NaN,...,NaN,38.0,5.0,M,NaN,1,NaN,1.0,NaN,2014-05-19
3,3000.0,17.0,2.0,4.0,7.0,3.0,5,1.0,1.0,NaN,...,NaN,43.0,6.0,F,4.0,1,4.0,1.0,NaN,2014-02-20
4,2690.0,21.0,4.0,3.0,6.0,2.0,4,1.0,NaN,NaN,...,NaN,39.0,5.0,F,4.0,0,4.0,NaN,NaN,2014-06-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280785,3230.0,37.0,5.0,4.0,11.0,2.0,5,1.0,0.0,1.0,...,2.0,39.0,5.0,1,4.0,1,4.0,1.0,0.0,2023-10-11
280786,3155.0,25.0,2.0,4.0,8.0,2.0,5,1.0,0.0,1.0,...,3.0,35.0,4.0,1,4.0,1,4.0,1.0,0.0,2024-01-22
280787,3040.0,24.0,5.0,4.0,9.0,2.0,5,1.0,0.0,1.0,...,2.0,38.0,5.0,1,4.0,1,4.0,1.0,0.0,2024-02-05
280788,3410.0,37.0,5.0,4.0,12.0,2.0,5,1.0,0.0,0.0,...,2.0,39.0,5.0,2,1.0,1,1.0,0.0,1.0,2023-02-21
280789,3795.0,26.0,3.0,4.0,10.0,1.0,5,1.0,1.0,0.0,...,3.0,39.0,5.0,2,1.0,1,1.0,1.0,0.0,2024-03-12

criando variável dependente com bweight < 2500 sendo baixo peso de acordo com a OMS

In [14]:
df['BAIXO_PESO'] = df['PESO'] < 2500

In [15]:
df['BAIXO_PESO'].value_counts()

BAIXO_PESO
False    256073
True      24717
Name: count, dtype: int64

analisando correalação entre variáveis

In [18]:
df['SEXO'] = df['SEXO'].apply(lambda x: 1 if x == 'M' else 0)

In [ ]:
df.corr()

,PESO,IDADEMAE,ESCMAE2010,CONSULTAS,CONSPRENAT,MESPRENAT,KOTELCHUCK,GRAVIDEZ,QTDPARTNOR,QTDPARTCES,PARTO,STCESPARTO,SEMAGESTAC,GESTACAO,SEXO,RACACORMAE,PARIDADE,DT_NASC,BAIXO_PESO
PESO,1.000000,0.029245,0.000749,0.103465,0.033250,-0.029617,0.046162,-0.229967,0.033617,0.046393,0.042079,-0.006478,0.538354,0.481713,0.022327,0.018610,0.081242,-0.001082,-0.656745
IDADEMAE,0.029245,1.000000,0.264601,0.109409,0.067224,-0.033310,0.090247,0.046186,0.243992,0.208539,0.203253,-0.117659,-0.067070,-0.023521,-0.027116,-0.150744,0.349735,0.007016,0.012923
ESCMAE2010,0.000749,0.264601,1.000000,0.154476,0.090265,-0.034912,0.141590,0.023863,-0.293054,-0.000076,0.218180,-0.118108,-0.044587,-0.004417,-0.029995,-0.237426,-0.149981,0.008696,-0.007019
CONSULTAS,0.103465,0.109409,0.154476,1.000000,0.752479,0.004613,0.371288,0.000774,-0.149609,0.000620,0.124790,-0.067315,0.117494,0.125160,-0.023353,-0.124548,-0.065726,0.006218,-0.091883
CONSPRENAT,0.033250,0.067224,0.090265,0.752479,1.000000,0.301541,0.389514,0.015087,-0.053481,-0.000829,0.052700,-0.017496,0.044385,0.045267,-0.009196,-0.064386,-0.026658,0.004480,-0.025821
MESPRENAT,-0.029617,-0.033310,-0.034912,0.004613,0.301541,1.000000,0.385229,0.004872,0.063745,-0.001836,-0.051481,0.067053,-0.020894,-0.028181,0.020560,0.051080,0.019884,-0.003717,0.028172
KOTELCHUCK,0.046162,0.090247,0.141590,0.371288,0.389514,0.385229,1.000000,0.006786,-0.097971,-0.001310,0.090597,-0.023416,0.054310,0.055622,-0.002391,-0.069069,-0.050356,-0.002526,-0.037208
GRAVIDEZ,-0.229967,0.046186,0.023863,0.000774,0.015087,0.004872,0.006786,1.000000,0.009617,0.003580,0.091889,-0.033206,-0.208578,-0.196601,-0.004673,-0.017886,0.010624,0.000795,0.263163
QTDPARTNOR,0.033617,0.243992,-0.293054,-0.149609,-0.053481,0.063745,-0.097971,0.009617,1.000000,-0.017445,-0.287185,0.136796,0.017108,-0.000325,0.009193,0.149526,0.407186,-0.003409,-0.002033
QTDPARTCES,0.046393,0.208539,-0.000076,0.000620,-0.000829,-0.001836,-0.001310,0.003580,-0.017445,1.000000,0.294886,-0.118180,-0.022453,0.004554,-0.012267,-0.029324,0.365973,0.004414,-0.020810
PARTO,0.042079,0.203253,0.218180,0.124790,0.052700,-0.051481,0.090597,0.091889,-0.287185,0.294886,1.000000,-0.398816,-0.044261,-0.004941,0.006154,-0.136762,-0.024130,-0.001907,0.017404
STCESPARTO,-0.006478,-0.117659,-0.118108,-0.067315,-0.017496,0.067053,-0.023416,-0.033206,0.136796,-0.118180,-0.398816,1.000000,0.035376,0.006220,-0.062300,0.126334,0.005328,0.001743,-0.009589
SEMAGESTAC,0.538354,-0.067070,-0.044587,0.117494,0.044385,-0.020894,0.054310,-0.208578,0.017108,-0.022453,-0.044261,0.035376,1.000000,0.860073,-0.000439,0.045538,-0.005170,0.001671,-0.490813
GESTACAO,0.481713,-0.023521,-0.004417,0.125160,0.045267,-0.028181,0.055622,-0.196601,-0.000325,0.004554,-0.004941,0.006220,0.860073,1.000000,0.001569,0.015377,0.006874,0.003622,-0.480710
SEXO,0.022327,-0.027116,-0.029995,-0.023353,-0.009196,0.020560,-0.002391,-0.004673,0.009193,-0.012267,0.006154,-0.062300,-0.000439,0.001569,1.000000,-0.001714,-0.016215,-0.048705,-0.007383
RACACORMAE,0.018610,-0.150744,-0.237426,-0.124548,-0.064386,0.051080,-0.069069,-0.017886,0.149526,-0.029324,-0.136762,0.126334,0.045538,0.015377,-0.001714,1.000000,0.057462,0.003036,-0.007657
PARIDADE,0.081242,0.349735,-0.149981,-0.065726,-0.026658,0.019884,-0.050356,0.010624,0.407186,0.365973,-0.024130,0.005328,-0.005170,0.006874,-0.016215,0.057462,1.000000,0.005509,-0.030246
DT_NASC,-0.001082,0.007016,0.008696,0.006218,0.004480,-0.003717,-0.002526,0.000795,-0.003409,0.004414,-0.001907,0.001743,0.001671,0.003622,-0.048705,0.003036,0.005509,1.000000,0.000038
BAIXO_PESO,-0.656745,0.012923,-0.007019,-0.091883,-0.025821,0.028172,-0.037208,0.263163,-0.002033,-0.020810,0.017404,-0.009589,-0.490813,-0.480710,-0.007383,-0.007657,-0.030246,0.000038,1.000000